### ISSUE TITLE
compile the hiq-decoder

### ISSUE THREAD

**Issue by 0502lian** [ouyangzhibo/HiQ-Robust-and-Fast-Decoding-of-High-Capacity-Color-QR-Codes#3]
May I ask how to compile the hiq-decoder?  Thanks  a  lot!

**Comment by DonaldTsang** [comment]
Same

**Comment by ouyangzhibo** [comment]
> May I ask how to compile the hiq-decoder? Thanks a lot!

The code is written in Java for Android platform. To compile it, you need to have the environment set up for Android development first. Then, you just need to import the code and the libraries in the repository.

**Comment by 0502lian** [comment]
> May I ask how to compile the hiq-decoder? Thanks a lot!
> 
> The code is written in Java for Android platform. To compile it, you need to have the environment set up for Android development first. Then, you just need to import the code and the libraries in the repository.

I have solved the problem. Thank you!

**Comment by DonaldTsang** [comment]
@ouyangzhibo pre-compiled apk would be even better.
